#


defaults: &defaults
  cool:
    saweet: nested settings
  hi: false
  easy_bonus: 1.2
  min_efactor: 130
  default_learning_mode_intervals: [1, 3]
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
  



development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults