defaults: &defaults
  cool:
    saweet: nested settings
  easy_bonus: 1.2
  minimum_e_factor: 130
  default_learning_mode_intervals: [1, 3]
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>



development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults